---
- name: connecting to all servers
  hosts: all 
  gather_facts: true
  become_method: yes
  tasks:
  - name: creating jenkins workspace folder
    file:
      path: /var/lib/jenkins
      state: directory
      owner: root
      group: root
      mode: 0775
    when: true
      
