---
- name: ping all servers
  hosts: dummy
  gather_facts: false
  become_method: yes 
  tasks:
  - name: pinging all servers
    ping:
 
  - name: print date using figlet 
    shell: date | figlet > /home/najite/figlet.txt

  - name: cat output of figlet
    shell: cat /home/najite/figlet.txt
    register: data 

  - name: print out the figlet result
    debug:
      msg: "{{ data.stdout }}"
