---
- name: installing items on CentOS server
  yum: name={{ item }} state=present
  with_items:
    - wget
    - vim
    - figlet
    - monitorix
    - python-pip
    - openvpn
    - MySQL-python
    - openssh-server
    - epel-release
  when: ansible_distribution == "CentOS"

